=begin
#SMS Fusion API

#This is the SMS Fusion API

OpenAPI spec version: 1.0.0
Contact: support@smsfusion.com.au
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::SMSApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SMSApi' do
  before do
    # run before each test
    @instance = SwaggerClient::SMSApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SMSApi' do
    it 'should create an instact of SMSApi' do
      expect(@instance).to be_instance_of(SwaggerClient::SMSApi)
    end
  end

  # unit tests for send_sms
  # Send an SMS
  # Send one or more SMS
  # @param key API Key as generated from the &lt;a href&#x3D;&#39;https://www.smsfusion.com.au/admin/api/&#39;&gt;admin panel&lt;/a&gt;
  # @param num Comma separated list of phone numbers or &lt;a href&#x3D;&#39;https://www.smsfusion.com.au/help/msisdn/&#39;&gt;MSDISDN&lt;/a&gt;&#39;s
  # @param msg Message content to send
  # @param [Hash] opts the optional parameters
  # @option opts [String] :from MSISDN or vanity alphanumeric source number
  # @option opts [String] :deliverby UTC encoded time to send the SMS
  # @option opts [String] :dlrcb HTTP or HTTPS callback URL for delivery reports. Timeout for callbacks is set to 30 seconds
  # @option opts [String] :replycb HTTP or HTTPS callback URL for replies. Timeout for callbacks is set to 30 seconds
  # @option opts [String] :replyemail Email address to send replies to
  # @option opts [Integer] :validity Time in minutes to keep the SMS valid for
  # @option opts [String] :cc 2 character country code &lt;a href&#x3D;&#39;https://en.wikipedia.org/wiki/ISO_3166-2&#39;&gt;ISO 3166-2&lt;/a&gt; for formatting local numbers internationally
  # @return [SMSResult]
  describe 'send_sms test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
