=begin
#SMS Fusion API

#This is the SMS Fusion API

OpenAPI spec version: 1.0.0
Contact: support@smsfusion.com.au
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::OutOfCredit
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'OutOfCredit' do
  before do
    # run before each test
    @instance = SwaggerClient::OutOfCredit.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OutOfCredit' do
    it 'should create an instact of OutOfCredit' do
      expect(@instance).to be_instance_of(SwaggerClient::OutOfCredit)
    end
  end
  describe 'test attribute "error"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

