=begin
#SMS Fusion API

#This is the SMS Fusion API

OpenAPI spec version: 1.0.0
Contact: support@smsfusion.com.au
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/hlr_callback'
require 'swagger_client/models/hlr_error'
require 'swagger_client/models/hlr_result'
require 'swagger_client/models/out_of_credit'
require 'swagger_client/models/sms_result'

# APIs
require 'swagger_client/api/hlr_api'
require 'swagger_client/api/sms_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
